export enum DailyDebitStatus {
  OPEN = 'OPEN',
  FAILED = 'FAILED',
  FREQUENTLY_FAILED = 'FREQUENTLY_FAILED',
  REJECTED = 'REJECTED',
  FREQUENTLY_REJECTED = 'FREQUENTLY_REJECTED',
  CANCELLED = 'CANCELLED',
  CLOSED = 'CLOSED',
}
